#!/bin/bash
source .zooconfig
eval "$(${dockerMachineCommand} env default)"

echo -n "Creating docker machine with name default..."
${dockerMachineCommand} create --driver virtualbox default
echo "done"

