#!/bin/bash
source .zooconfig
eval "$(docker-machine env default)"

case $1 in
  image)
    docker rmi whynotsoluciones/${projectName}-argon:latest
    ;;
  container)
    docker rm ${projectName}
    ;;
  *)
    docker rm ${projectName}
    docker rmi whynotsoluciones/${projectName}-argon:latest
    ;;
esac
