#!/bin/bash

# Create/upgrade the image
#docker build -t whynotsoluciones/node-argon .

# Push it to docker hub
#docker push whynotsoluciones/node-argon

# Note the name of the image and the latest ID to notify other users
REPO="whynotsoluciones"
IMAGE="node-argon"
TAG="latest"

sed -i -e 's/.*${REPO}.*${IMAGE}.*${TAG}.*/"${REPO}\/${IMAGE}:${TAG}|$(date +%s)"/' `pwd`/.dockerimages

