#!/bin/bash
source .zooconfig
eval "$(${dockerMachineCommand} env default)"

docker pull whynotsoluciones/${projectName}-node:latest
docker-tools/docker-clean-all container

echo "Docker image updated"

