#!/bin/bash
source .zooconfig
eval "$(docker-machine env default)"

./docker-tools/docker-stop
./docker-tools/docker-clean-all image
./docker-tools/docker-clean-all container

# Create/upgrade the image
docker build -t whynotsoluciones/${projectName}-node .

# Push it to docker hub
docker push whynotsoluciones/${projectName}-node

# Note the name of the image and the latest ID to notify other users
REPO="whynotsoluciones"
IMAGE="${projectName}-node"
TAG="latest"

if [ ! -f `pwd`/.dockerimages ];
then
  touch `pwd`/.dockerimages
  echo "$REPO/$IMAGE:$TAG" > `pwd`/.dockerimages
fi

sed -i '' -e "s/.*${REPO}.*${IMAGE}.*${TAG}.*/${REPO}\/${IMAGE}:${TAG}|$(date +%s)/" `pwd`/.dockerimages

