#!/bin/bash
source .zooconfig
eval "$(docker-machine env default)"

# Check if container exists
docker ps | if grep --silent ${projectName}
then
  echo "Container already running. Use connect command."
  exit 1
else

  docker ps -a | if grep --silent ${projectName}
  then
    echo "Using existing container."
    docker start -i -a ${projectName}
  else
    # Create container
    echo -n "Container not found: creating new and running. "
    docker run                                \
        -h ${projectName}                     \
        -p $apiPort:4000                      \
        -p 27017:27017                        \
        -v $srcDir:/usr/src                   \
        --name="${projectName}"                        \
        whynotsoluciones/${projectName}-node:latest    \
        npm run start
    echo "Container stopped. Bye!"
  fi

fi

